### ISSUE TITLE
Very slow rendering at Chrome v48.0.2564.97 (64-bit)

### ISSUE THREAD

**Issue by sifue** [GitbookIO/gitbook#1124]
It's to hard to read https://help.gitbook.com/ by Chrome v48.0.2564.97 (64-bit)
Firefox and Safari have no problem.

**Comment by sifue** [comment]
`sed -i 's/text-rendering:optimizeLegibility;//' style.css` is a solution to this problem.

**Comment by sifue** [comment]
I write follows.

```css:styles/website.css
body {
  text-rendering: auto;
}
```

```json:book.json
{
    "styles": {
        "website": "styles/website.css"
    }
}
```
