### ISSUE TITLE
CSS classes for "alert alert-warning" etc. are missing in PDFs

### ISSUE THREAD

**Issue by Tiliavir** [GitbookIO/gitbook#1238]
Some CSS classes, e.g., for "alert alert-warning" etc. are missing / not working in generated PDFs. Hence mentioned blocks are not highlighted in PDFs...

**Comment by Tiliavir** [comment]
As a workaround add this CSS to styles/pdf.css

```css
.alert {
    color: #444;
    padding: 15px;
    margin-bottom: 20px;
    background: #eee;
    border-bottom: 5px solid #ddd;
}
.alert-success {
    background: #dff0d8;
    border-color: #d6e9c6;
    color: #3c763d;
}
.alert-info {
    background: #d9edf7;
    border-color: #bce8f1;
    color: #31708f;
}
.alert-danger {
    background: #f2dede;
    border-color: #ebccd1;
    color: #a94442;
}
.alert-warning {
    background: #fcf8e3;
    border-color: #faebcc;
    color: #8a6d3b;
}
```
