### ISSUE TITLE
How to remove “Published with Gitbook” 

### ISSUE THREAD

**Issue by sirarpikasabyan** [GitbookIO/gitbook#1404]
Hi ! Is it possible to remove “Published with Gitbook” at the end of table of contents? If yes, how ?
Thanks

**Comment by dorako321** [comment]
please create `styles/website.css`
```css
.gitbook-link {
    display: none !important;
}
```
then, edit `book.json`

```json
{
    "styles": {
        "website": "styles/website.css"
    }
}
```
