### ISSUE TITLE
Header should be stretched on mobile viewport

### ISSUE THREAD

**Issue by erixtekila** [GitbookIO/gitbook#162]
Changing the header's buttons styles permit to fit in mobile available space

``` css
.book .book-header .btn {
   padding : 0 5px;
}
```

You may also use a dedicated media query.

Or maybe removing the words "WATCH" and "STAR" ?
