### ISSUE TITLE
.// in the fonts path : 404 error

### ISSUE THREAD

**Issue by benjaminach** [GitbookIO/gitbook#511]
Hello,

@staticPath is set tp "./"
and 
@FontPath is set to "{staticPath}/fonts"

So, in the generated CSS the font folder is ".//fonts"

``` css
@font-face{
    font-family:'FontAwesome';
    src:url('.//fonts/fontawesome/fontawesome-webfont.eot?v=4.1.0');
}

@font-face{
    font-family:'Merriweather';
    src:local('Merriweather Light'),url('.//fonts/merriweather/250.woff') format('woff')
}
```

Maybe this is not a problem for Apache, but this is not good for Amazon S3 :)
Have you this issue to ?
