### ISSUE TITLE
Long codelines in exported PDF broken

### ISSUE THREAD

**Issue by fnordian** [GitbookIO/gitbook#752]
Hi,

When gitbook renders a book with long lines of code to PDF, the result contains static, non-functional scrollbars. This looks very ugly.

Marcus

**Comment by jashaj** [comment]
What worked for me:

```css
pre {
  word-break: break-all;
  /* Non standard for webkit, but it does work on the Mac when generating the PDF */
  word-break: break-word;
}
```
