### ISSUE TITLE
Right .navigation-next bar makes scrollbar unusable

### ISSUE THREAD

**Issue by Fannon** [GitbookIO/gitbook#800]
Hello there,

on the latest Chrome, the right `a.navigation-next` element prevents me from using the scrollbar with mouseclicks.

This CSS fixed it for me:

``` css
.book .book-body .navigation.navigation-next {
    right: 18px;
}
```

The element has a `style="margin-right: 17px;` on it, this should be removed, the CSS above fixes the problem in a better way.
