### ISSUE TITLE
unnumbered items in the table of contents?

### ISSUE THREAD

**Issue by jfix** [GitbookIO/gitbook#810]
Hi, 

maybe I just haven't found the option yet, but it seems like there is no way to not have the table of contents behave like a numbered list.  I actually have a table of contents (over which I have no control) that has its own numbering scheme of "Article 1 on this" and "Article 2 on that" etc.

Thanks for pointers,
Jakob.

**Comment by SamyPesse** [comment]
This can be done using a custom stylesheets, **styles/website.css**:

```css
.book-summary .summary .chapter b {
     display: none;
}
```
